---
# tasks file for ansible-role-azcopy
- name: azcopy - download and install
  unarchive:
    src: '{{ azcopy_download_url }}'
    dest: /tmp
    remote_src: yes

- name: azcopy - copy to install dir
  copy:
    src: '/tmp/{{ azcopy_unzip_subfoldername }}/{{ azcopy_filename_exe }}'
    dest: '{{ azcopy_install_dir }}/{{ azcopy_filename_exe }}'
    remote_src: yes
    owner: '{{ azcopy_file_owner }}'
    group: '{{ azcopy_file_group }}'
    mode: '{{ azcopy_file_mode }}'

- name: azcopy - Delete temporary extract dir
  file:
    path: '/tmp/{{ azcopy_unzip_subfoldername }}'
    state: absent